name: Auto Checkin

on:
  schedule:
    # 每天北京时间早上9点运行
    - cron: '0 1 * * *'
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
        
    - name: Create .env file
      run: |
        echo "LOGIN_URL=${{ secrets.LOGIN_URL }}" > .env
        echo "CHECKOUT_URL=${{ secrets.CHECKOUT_URL }}" >> .env
        echo "LOGOUT_URL=${{ secrets.LOGOUT_URL }}" >> .env
        echo "USEREMAIL=${{ secrets.USEREMAIL }}" >> .env
        echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
        
    - name: Run check-in script
      run: python jiaoben.py
      
    - name: Clean up .env
      run: rm -f .env
